#!/bin/sh

# Update pkg to use latest
mkdir -p /usr/local/etc/pkg/repos
echo 'FreeBSD: {
  url: "pkg+http://pkg.FreeBSD.org/${ABI}/latest",
  mirror_type: "srv",
  signature_type: "fingerprints",
  fingerprints: "/usr/share/keys/pkg",
  enabled: yes
}' > /usr/local/etc/pkg/repos/FreeBSD.conf

# Update pkg definitions
pkg update
pkg upgrade

# install basic packages
pkg -y install rcadm sshguard

# setup ssh key access
mkdir ~/.ssh
touch ~/.ssh/authorized_keys
chmod 0700 ~/.ssh
chmod 0600 ~/.ssh/authorized_keys

# setup ipfw
